In [31]:
from qiskit import QuantumCircuit, Aer, assemble
from math import pi
import numpy as np
from qiskit.visualization import plot_histogram, plot_bloch_multivector

In [32]:
qc = QuantumCircuit(2)

In [33]:
qc.draw()

q_0: 
     
q_1:

In [34]:
qc.h(0)
qc.cx(0,1)
qc.x(1)

In [35]:
qc.draw()

┌───┐          
q_0: ┤ H ├──■───────
     └───┘┌─┴─┐┌───┐
q_1: ─────┤ X ├┤ X ├
          └───┘└───┘

┌───┐     
q_0: ┤ H ├──■──
     └───┘┌─┴─┐
q_1: ─────┤ X ├
          └───┘

In [36]:
svsim = Aer.get_backend('statevector_simulator')
qobj = assemble(qc)
final_state = svsim.run(qobj).result().get_statevector()


In [37]:
final_state

array([0.        +0.j, 0.70710678+0.j, 0.70710678+0.j, 0.        +0.j])

┌───┐     
q_0: ┤ H ├──■──
     └───┘┌─┴─┐
q_1: ─────┤ X ├
     ┌───┐├───┤
q_2: ┤ X ├┤ H ├
     └───┘└───┘
q_3: ──────────
               
q_4: ──────────

┌───┐               
q_0: ┤ H ├──■────────────
     └───┘┌─┴─┐          
q_1: ─────┤ X ├───────■──
     ┌───┐├───┤     ┌─┴─┐
q_2: ┤ X ├┤ H ├──■──┤ X ├
     └───┘└───┘┌─┴─┐└───┘
q_3: ──────────┤ X ├─────
               └───┘     
q_4: ────────────────────

In [12]:
svsim = Aer.get_backend('statevector_simulator')
qobj = assemble(qc)
final_state = svsim.run(qobj).result().get_statevector()



In [13]:
final_state

array([ 0.5-6.123234e-17j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0.5-6.123234e-17j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j, -0.5+6.123234e-17j,
       -0.5+6.123234e-17j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j,  0. +0.000000e+00j,
        0. +0.000000e+00j,  0. +0.000000e+00j])

In [16]:
usim = Aer.get_backend('unitary_simulator')
qobj = assemble(qc)
unitary = usim.run(qobj).result().get_unitary()

In [17]:
unitary

array([[ 0.5-6.1232340e-17j,  0.5-1.2246468e-16j,  0. +0.0000000e+00j,
        ...,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0.5-6.1232340e-17j,
        ...,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
        ...,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j],
       ...,
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
        ...,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
        ...,  0. +0.0000000e+00j,  0.5+0.0000000e+00j,
         0.5-6.1232340e-17j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
        ..., -0.5+6.1232340e-17j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j]])